---
- name: Get MAC information
  hosts: all
  gather_facts: false

  tasks:
    - name: show mac address-table
      raw: "show mac address-table"

      register: print_output
    - debug: var=print_output.stdout_lines